MOUSEKEY_ENABLE     = no      # Mouse keys
RGBLIGHT_ENABLE     = yes     # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes
OLED_ENABLE         = yes
OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = no
COMBO_ENABLE        = no
TAP_DANCE_ENABLE 	= no
KEY_OVERRIDE_ENABLE = no
# BACKLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = no
# LED_MATRIX_ENABLE = no